# Generated by Django 4.1.4 on 2023-02-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'draft')], default='active', max_length=10),
        ),
    ]
