# Generated by Django 4.1.4 on 2023-02-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_category_author_category_created_at_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='intro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'draft')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'draft')], default='active', max_length=10),
        ),
    ]
